### ISSUE TITLE
GC update는 언제 해주나요 ? 

### ISSUE THREAD

**Issue by wkdtndgns** [shouwn/Thread#1]
tls도

**Comment by shouwn** [comment]
GC는 할당된 메모리가 가득 차게 되면 작동됩니다.

Young 영역에서 GC가 작동되는 경우는

eden 이 가득 찼을 경우, survive 영역이 가득 찼을 경우 입니다.

각각 eden이 가득 차면 GC를 한 뒤에 남은 것들을 survive 영역에 옮기고

survive 영역이 가득 차면 GC가 실행되고 남은 것들이 old로 갑니다. 

old 또한 마찬가지로 GC를 하면 남은 것들은 다른 영역으로 옮겨 컴팩하게 됩니다.

**Comment by wkdtndgns** [comment]
eden 에서 survive 으로 
survive에서 old로 가는 과정을 자세히 설명해주실 수 있나요??

ex) 가득차는 과정 번갈아가면서 하나씩 증가한다던지

**Comment by shouwn** [comment]
맨 처음 객체가 생성되면 eden 영역에 할당됩니다. 그 후 eden영역이 가득 차면 GC가 되는데

먼저 참조되는 객체들과 참조되지 않는 개첵들을 mark 합니다. 그리고 참조되는 객체를 survive 영역으로 옮기고 나머지는 free 하게 됩니다. 그러면 eden 영역은 비게 되고 다시 객체를 할당할 수 있게 됩니다. 

다음으로 survive 영역입니다. survive 영역은 1 과 2로 나뉘어져 있습니다. 이 이유는 압축 때문입니다. 먼저 eden에서 온 객체를 현재 사용하고 있는 survive 영역에 넣습니다. 이를 1이라고 이야기 하도록 하겠습니다. 

1에 eden에서 온 객체를 넣고 survive 1이 가득 차면 GC를 합니다. 똑같이 mark를 하고 참조되는 객체들을 survive 2에 넣습니다. 넣을 때는 차곡 차곡 쌓습니다. 이렇게 계속 반복합니다.

이렇게 하면서 얻을 수 있는 장접은 압축입니다. 만약 survive 하나만 사용하고 여기서 사용되지 않는 객체를 free 시키면 사용될 수 있는 메모리가 파편처럼 조각 조각 나뉘게 됩니다. 이러면 마음대로 메모리를 배정할 수 없고 빈 공간을 찾아야 하고 메모리는 남지만 객체를 넣을 공간이 비좁에 객체를 할당할 수 없게 됩니다. 이와 같은 단점을 회피하기 위해서 1과 2로 나뉘어 계속 교환하며 GC를 합니다. 

그 뒤 이를 카운트 하여 오래 살아 남은 객체들은 old 영역으로 이전 시키는데 old 영역도 survive와 마찬가지로 2가지 공간으로 나뉘어서 GC를 합니다.
