### ISSUE TITLE
 context switching 에 대해 궁금중 

### ISSUE THREAD

**Issue by wkdtndgns** [shouwn/Thread#2]
context switching 으로 싱글코어면 잠시 동안 쓰레드 일을 하고 다른 쓰레드로 넘어가기에 같이 되는것처럼 보인다고 했는데  3개의 쓰레드를 듀얼코어로 돌리면 3개중 2개가 cpu하나씩 들어가고 잠시 뒤 하나는 둘중에 하나로 매치될텐데 매치되는 기준이 먼가여?

**Comment by shouwn** [comment]
모든 작업은 운영체제가 관리하기 때문에, 사용하시는 운영체제 문서를 확인하셔야 할 것 같습니다.
